context:
  listener:
    classes: com.fewok.server.component.ApplicationEventListener

logging:
  config: classpath:log4j2.xml

management:
  server:
    port: 34613
    servlet:
      context-path: /projectManage

spring:
  aop:
    auto: true
    proxy-target-class: false  #基于标准的基于Java接口的代理
  application:
    name: "fewok"
  cache:
    type: caffeine
  freemarker:
    cache: false
    enabled: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  mvc:
    favicon:
      enabled: false
  profiles:
    active: dev
  session:
    store-type: none
  webservices:
    path: /
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB
  transaction:
    default-timeout: 10000ms
    rollback-on-commit-failure: true




server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048
  connection-timeout: 10000ms
  error:
      path: /error #错误页，指定发生错误时，跳转的URL
      whitelabel:
        enabled: true #在服务器发生错误的情况下，启用浏览器中显示的默认错误页面。
  port: 39368
  use-forward-headers: true #如果X-Forwarded- *头应该应用于HttpRequest。
  servlet:
    context-path: /  #应用程序的上下文路径。
    application-display-name: "fewok"
    path: /  #主调度程序servlet的路径。
  undertow:  #其他缓存、线程配置，默认即可
    accesslog:
      dir: /opt/logs/fewok/access
      enabled: true
      # 访问时间 线程名 '本机IP:端口/远程主机的IP:端口' '请求方式 请求路径 请求协议'  HTTP状态码  '处理请求所耗费的毫秒数/秒数' '发送字节数' '内容类型'
      pattern: "%t %I '%A:%p/%a:%p' '%m %U %H' %s '%D ms=%T s' '%b/%B/%{o,Content-Length}' '%{o,Content-Type}' '%{i,User-Agent}' '%{i,Referer}'"
      rotate: true



